### ISSUE TITLE
autocompletion + difference from c pkg

### ISSUE THREAD

**Issue by ngam** [conda-forge/tldr-feedstock#2]
Hey friend! Would you like a second maintainer to ensure no loneliness here? Big fan of this nifty utility :)

Have you tested the autocompletion feature? It doesn't seem to work for me... Also, this is the python client; are there any differences or any potential dis/advantages of building the c pkg?

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by izahn** [comment]
Yes, the more the merrier!

I packaged the python implementation because a) it looks well maintained, b) python is easy to package for conda-forge, and c) that is what Arch Linux packages. The closest thing to an "official" command line client is the npm version according to https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients but it didn't seem so much better as to justify the more difficult exercise of packaging npm packages for conda-forge.

The documentation instructions for enabling autocomplete but I haven't looked into it: https://github.com/tldr-pages/tldr-python-client#autocomplete

**Comment by ngam** [comment]
I see. Agree with the ease and perhaps maintenance of python as opposed to c, etc. 

I will submit an issue to get me added here
